#!/bin/sh

action=$1

if [ "$action" = "init" ]; then

	git checkout --orphan develop
	rm -rf ./*

	echo "* Pushing to github"
	git push --set-upstream origin develop

	# back to master
	git checkout master

elif [ "$action" = "add" ]; then
	pkg=$2
	prefix=$pkg/pkg
	if [ "$3" != "" ]; then prefix=$3/pkg/$pkg; fi
	pkgdir=`dirname $prefix`
	git checkout develop
	mkdir -p $pkgdir
	touch $pkgdir/.gitignore
	git add $pkgdir
	git commit -m "Add package $pkg as ${prefix}/ sub-directory"
	git remote add -f $pkg https://github.com/renozao/${pkg}.git
	git subtree add --prefix=$prefix $pkg develop --squash

	echo "* Pushing to github"
	#git push

	# back to master
	#git checkout master

elif [ "$action" = "update" ]; then
	# update source code for R-forge to fetch

	update_packages()
	{
		local dir 
		local prefix=/pkg
		for dir in $1/*/
		do
		    dir=`echo ${dir%*/} | sed -e 's/\.\///'`
		    if [ -f "${dir}/pkg/DESCRIPTION" ]
		    then
			echo "## Updating package $dir in `pwd`"
			echo "git subtree pull --prefix=$dir$prefix $dir develop --squash"
			echo "##"   
			echo
		    else
			update_packages ${dir}/pkg
		    fi
		done
	}

	update_packages .
	#git checkout develop

	echo "* Pushing to github"
	#git push

	# back to master
	#git checkout master

elif [ "$action" = "gh" ]; then

	# update static pages
	git checkout gh-pages
	for dir in ./web/*/
	do
	    dir=`echo ${dir%*/} | sed -e 's/\.\/web\///'`
	    echo ${dir}
	    #git subtree pull --prefix=web/${dir} $dir gh-pages:develop
	done
	
	git checkout master
fi


