#!/bin/sh

action=$1

if [ "$action" = "init" ]; then

	git checkout --orphan develop
	rm -rf ./*

	echo "* Pushing to github"
	git push --set-upstream origin develop

	# back to master
	git checkout master

elif [ "$action" = "add" ]; then
	pkg=$2
	prefix=$pkg/pkg
	if [ "$3" != "" ]; then prefix=$3/pkg/$pkg; fi
	pkgdir=`dirname $prefix`
	git checkout develop
	if [ ! -d $pkgdir ]; then
		mkdir -p $pkgdir
		touch $pkgdir/.gitignore
		git add $pkgdir
		git commit -m "Create package subtree $pkgdir/ parent directory"
	fi
	echo "* Adding package $pkg as ${prefix}/ sub-directory"
	if [ -d $prefix ]; then
		echo "warning: subtree $prefix already exists -> aborting adding package"
	else
		git remote add -f $pkg https://github.com/renozao/${pkg}.git
		git subtree add --prefix=$prefix $pkg develop --squash
	fi
	
	echo "* Pushing to github"
	git push

	# back to master
	git checkout master

elif [ "$action" = "update" ]; then
	# update source code for R-forge to fetch

	update_packages()
	{
		local dir
		for dir in $1/*/
		do
		    dir=`echo ${dir%*/} | sed -e 's/\.\///'`
		    local pkg=$dir
		    local prefix=$dir/pkg

		    if [ ! -z $2 ]; then 
			pkg=`basename $dir`
			prefix=$dir
	    	    fi

		    if [ -f "${prefix}/DESCRIPTION" ]; then
			echo "** Updating package $pkg in $prefix"
			git subtree pull --prefix=$prefix $pkg develop --squash
			echo "##"   
			echo
		    elif [ -d "$dir/pkg" ]; then
			update_packages ${dir}/pkg true
		    elif [ ! -f "$1/DESCRIPTION" ]; then
			echo "** Skipping directory $prefix: no package found" 
		    fi
		done
	}

	git checkout develop
	update_packages .

	echo "* Pushing to github"
	git push

	# back to master
	git checkout master

elif [ "$action" = "gh" ]; then

	# update static pages
	git checkout gh-pages
	for dir in ./web/*/
	do
	    dir=`echo ${dir%*/} | sed -e 's/\.\/web\///'`
	    echo ${dir}
	    #git subtree pull --prefix=web/${dir} $dir gh-pages:develop
	done
	
	git checkout master
fi


